### ISSUE TITLE
Que-View assumes you are using DelayedJob

### ISSUE THREAD

**Issue by philmunt** [kortirso/que-view#21]
We tried to use Que View but we are using Que directly, not with delayed job.

This fails because the HTML view is expecting the arguments to be in a structure
consistent with the DelayedJob Que adapter.

See: app/views/que/view/jobs/index.html.erb

```erb
        <td>
          <% Array(job.dig(:args, 0, :arguments)).each do |argument| %>
            <p><%= argument %></p>
          <% end %>
        </td>
```

I didn't check if this is the case elsewhere. We've decided to roll our own specialised interface now, but I though since you guys appear to be so active you might be interested in supporting this use case.

**Comment by kortirso** [comment]
hi @philmunt, interesting

so do queue your jobs something like `ChargeCreditCard.enqueue(...)` from que's example? and in this case is job's record in database different?

**Comment by kortirso** [comment]
@philmunt I published new version, should renders simple Que jobs
